/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'popularStyles' : IDL.Opt(IDL.Vec(IDL.Nat)),
});
export const Style = IDL.Record({
  'id' : IDL.Nat,
  'categoryId' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'image' : IDL.Text,
  'price' : IDL.Float64,
});
export const CatalogResponse = IDL.Record({
  'categories' : IDL.Vec(Category),
  'styles' : IDL.Vec(Style),
});
export const Time = IDL.Int;
export const Measurement = IDL.Record({
  'backRise' : IDL.Float64,
  'cuffCircumference' : IDL.Float64,
  'chest' : IDL.Float64,
  'bicepCircumference' : IDL.Float64,
  'frontRise' : IDL.Float64,
  'sleeveLength' : IDL.Float64,
  'shoulder' : IDL.Float64,
  'inseam' : IDL.Float64,
  'length' : IDL.Float64,
  'waist' : IDL.Float64,
  'hipCircumference' : IDL.Float64,
  'thighCircumference' : IDL.Float64,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'contactInfo' : IDL.Text,
  'orderStatus' : IDL.Text,
  'orderDate' : Time,
  'measurement' : Measurement,
  'style' : IDL.Nat,
  'category' : IDL.Nat,
  'price' : IDL.Float64,
});

export const idlService = IDL.Service({
  'getCatalog' : IDL.Func([], [CatalogResponse], ['query']),
  'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'submitInquiry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
  'submitOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, Measurement],
      [Order],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'popularStyles' : IDL.Opt(IDL.Vec(IDL.Nat)),
  });
  const Style = IDL.Record({
    'id' : IDL.Nat,
    'categoryId' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'image' : IDL.Text,
    'price' : IDL.Float64,
  });
  const CatalogResponse = IDL.Record({
    'categories' : IDL.Vec(Category),
    'styles' : IDL.Vec(Style),
  });
  const Time = IDL.Int;
  const Measurement = IDL.Record({
    'backRise' : IDL.Float64,
    'cuffCircumference' : IDL.Float64,
    'chest' : IDL.Float64,
    'bicepCircumference' : IDL.Float64,
    'frontRise' : IDL.Float64,
    'sleeveLength' : IDL.Float64,
    'shoulder' : IDL.Float64,
    'inseam' : IDL.Float64,
    'length' : IDL.Float64,
    'waist' : IDL.Float64,
    'hipCircumference' : IDL.Float64,
    'thighCircumference' : IDL.Float64,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'contactInfo' : IDL.Text,
    'orderStatus' : IDL.Text,
    'orderDate' : Time,
    'measurement' : Measurement,
    'style' : IDL.Nat,
    'category' : IDL.Nat,
    'price' : IDL.Float64,
  });
  
  return IDL.Service({
    'getCatalog' : IDL.Func([], [CatalogResponse], ['query']),
    'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'submitInquiry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
    'submitOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, Measurement],
        [Order],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };