/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CatalogResponse {
  'categories' : Array<Category>,
  'styles' : Array<Style>,
}
export interface Category {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'popularStyles' : [] | [Array<bigint>],
}
export interface Measurement {
  'backRise' : number,
  'cuffCircumference' : number,
  'chest' : number,
  'bicepCircumference' : number,
  'frontRise' : number,
  'sleeveLength' : number,
  'shoulder' : number,
  'inseam' : number,
  'length' : number,
  'waist' : number,
  'hipCircumference' : number,
  'thighCircumference' : number,
}
export interface Order {
  'id' : bigint,
  'customerName' : string,
  'contactInfo' : string,
  'orderStatus' : string,
  'orderDate' : Time,
  'measurement' : Measurement,
  'style' : bigint,
  'category' : bigint,
  'price' : number,
}
export interface Style {
  'id' : bigint,
  'categoryId' : bigint,
  'name' : string,
  'description' : string,
  'image' : string,
  'price' : number,
}
export type Time = bigint;
export interface _SERVICE {
  'getCatalog' : ActorMethod<[], CatalogResponse>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'submitInquiry' : ActorMethod<[string, string, string], boolean>,
  'submitOrder' : ActorMethod<
    [string, string, bigint, bigint, Measurement],
    Order
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];